print ('Bom dia amigos')
nome_usuario = 'Emanuelly Fernandes' # tipo -> str = string
idade_usuario = 18 # tipo -> int = integer
altura_usuario = 1.50 # tipo -> float = ponto flutuante
maior_idade = True # tipo -> bool = boolean 
print ('Seja bem-vindo',nome_usuario)
print ('sua idade é',idade_usuario, 'anos')
print ('você tem',altura_usuario, 'metros')
print ('você é maoir de idade?', maior_idade)